repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2  # Use the latest stable version
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format  # Optional, if you want Ruff to handle formatting instead of Black

  - repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest stable version
    hooks:
      - id: black
